// Sidebar menu sections — reorganized IA (iter 485). All ids/testIds preserved.
// `core: true` marks items visible in Simple mode (~30 essential screens).
import {
  Coins,
  Pulse,
  Handshake,
  AddressBook,
  ArrowSquareOut,
  ArrowsClockwise,
  Bed,
  Bell,
  BookOpen,
  Brain,
  Briefcase,
  Broom,
  Bug,
  Buildings,
  Calculator,
  CalendarBlank,
  ChartBar,
  ChartPieSlice,
  ChartLine,
  ChartLineUp,
  ChatText,
  Clock,
  CloudArrowUp,
  Code,
  Confetti,
  CreditCard,
  Crown,
  CurrencyDollar,
  DeviceMobile,
  DeviceTablet,
  Envelope,
  Eye,
  FileArrowDown,
  FileText,
  FilmReel,
  ForkKnife,
  Funnel,
  Gear,
  Globe,
  GraduationCap,
  GridFour,
  Headset,
  Heart,
  House,
  Key,
  Layout,
  Lightning,
  Link,
  Lock,
  MagicWand,
  MapPin,
  Megaphone,
  Microphone,
  Moon,
  Notebook,
  Package,
  PaintBrush,
  Palette,
  PlugsConnected,
  Plus,
  Receipt,
  Robot,
  Scales,
  Scroll,
  ShieldCheck,
  ShieldWarning,
  SignIn,
  Smiley,
  Sparkle,
  SquaresFour,
  Stack,
  Star,
  Storefront,
  Tag,
  Target,
  TestTube,
  Tray,
  TrendUp,
  Trophy,
  Umbrella,
  Upload,
  UserPlus,
  Users,
  UsersThree,
  Wallet,
  Warning,
  WhatsappLogo,
  Wrench,
  HourglassMedium,
  Bank,
  LockKey,
  GitBranch,
  UserMinus,
} from "@phosphor-icons/react";

export function buildMenuSections(t, user) {
  return [
    {
      label: "Overview",
      color: "text-stone-500",
      items: [
        { id: "dashboard", icon: House, name: t("nav.dashboard"), testId: "dashboard-btn", core: true },
        { id: "my-tasks", icon: Target, name: "My tasks", testId: "my-tasks-btn", core: true },
        { id: "calendar", icon: CalendarBlank, name: "Calendar", testId: "sidebar-calendar", core: true },
        { id: "availability-calendar", icon: CalendarBlank, name: "Müsaitlik Takvimi", testId: "availability-calendar-btn", core: true },
        { id: "tier1-dashboard", icon: ChartBar, name: "Master dashboard", testId: "tier1-dashboard-btn" },
        { id: "key-figures", icon: ChartPieSlice, name: "Anahtar göstergeler", testId: "key-figures-btn" },
        { id: "morning-brief", icon: ChartLine, name: "Morning brief", testId: "morning-brief-btn" },
        { id: "nightly-recap", icon: Moon, name: "Nightly recap", testId: "nightly-recap-btn" },
        { id: "custom-dashboard", icon: GridFour, name: "Custom Dashboard", testId: "custom-dashboard-btn" },
      ],
    },
    {
      label: "Reservations",
      color: "text-stone-500",
      items: [
        { divider: true, label: "Front Desk" },
        { id: "arrivals", icon: Bed, name: "Arrivals cockpit", testId: "arrivals-btn", core: true },
        { id: "walkin", icon: UserPlus, name: "Walk-in", testId: "walkin-btn", core: true },
        { id: "unified-inbox", icon: Tray, name: "Unified inbox", testId: "unified-inbox-btn", core: true },
        { id: "no-show", icon: Bell, name: "No-show charges", testId: "no-show-btn" },
        { id: "late-checkout", icon: Clock, name: "Late check-out", testId: "late-checkout-btn" },
        { id: "ci-slots", icon: Clock, name: "Check-in time slots", testId: "ci-slots-btn" },
        { id: "stay-ext", icon: Plus, name: "Stay extension", testId: "stay-ext-btn" },
        { id: "rebook", icon: ArrowsClockwise, name: "Quick re-booking", testId: "rebook-btn" },
        { id: "collisions", icon: ShieldCheck, name: "Collisions", testId: "collisions-btn" },
        { id: "res-quality", icon: ShieldCheck, name: "Rezervasyon kalite kontrolü", testId: "res-quality-btn" },

        { divider: true, label: "Desk Journal" },
        { id: "reception-report", icon: Notebook, name: "Reception report", testId: "reception-report-btn" },
        { id: "pass-over", icon: Notebook, name: "Pass-over duties", testId: "pass-over-btn" },
        { id: "logbook", icon: Notebook, name: t("nav.logbook"), testId: "logbook-btn", core: true },
        { id: "lost-found", icon: Eye, name: "Lost & found", testId: "lost-found-btn" },

        { divider: true, label: "Groups" },
        { id: "group-bookings", icon: Users, name: "Group bookings", testId: "group-bookings-btn" },
        { id: "group-blocks", icon: Users, name: "Group blocks", testId: "group-blocks-btn" },
        { id: "group-requests", icon: Users, name: "Group requests", testId: "group-requests-btn" },
        { id: "group-rooming", icon: FileText, name: "Group rooming import", testId: "group-rooming-btn" },
        { id: "group-rooming-wiz", icon: Users, name: "Group rooming wizard", testId: "group-rooming-wiz-btn" },
      ],
    },
    {
      label: "Direct Booking",
      color: "text-stone-500",
      items: [
        { id: "booking", icon: Bed, name: t("nav.booking"), testId: "booking-engine-btn", core: true },
        { id: "booking-engine-admin", icon: Globe, name: "Booking engine setup", testId: "booking-engine-admin-btn" },
        { id: "booking-engine-v2", icon: Package, name: "Booking engine v2 (paket & upsell)", testId: "booking-engine-v2-btn" },
        { id: "promo-codes", icon: Tag, name: t("nav.promo_codes"), testId: "promo-codes-btn" },
        { id: "add-ons", icon: Package, name: t("nav.add_ons"), testId: "add-ons-btn" },
        { id: "policies", icon: Scroll, name: t("nav.policies"), testId: "policies-btn" },
        { id: "long-stay", icon: CalendarBlank, name: "Long-stay discount", testId: "long-stay-btn" },
        { id: "cancel-insurance", icon: ShieldCheck, name: "Cancellation insurance", testId: "cancel-insurance-btn" },
        { id: "website-templates", icon: Layout, name: "Website templates", testId: "website-templates-btn" },
        { id: "customize-template", icon: PaintBrush, name: "Template customizer", testId: "customize-template-btn" },
        { id: "direct-conversion", icon: Sparkle, name: "Direct Booking Conversion", testId: "direct-conversion-btn" },
        { id: "web-concierge", icon: ChatText, name: "AI Web Concierge", testId: "web-concierge-btn" },
      ],
    },
    {
      label: "Guests & Loyalty",
      color: "text-stone-500",
      items: [
        { divider: true, label: "Profiles & CRM" },
        { id: "guest-profiles", icon: AddressBook, name: t("nav.guest_profiles"), testId: "guest-profiles-btn", core: true },
        { id: "crm-360", icon: Users, name: "Guest CRM 360", testId: "crm-360-btn", core: true },
        { id: "guest-risk", icon: ShieldWarning, name: "Misafir risk radarı", testId: "guest-risk-btn" },
        { id: "waitlist", icon: HourglassMedium, name: "Bekleme listesi", testId: "waitlist-btn" },
        { id: "guest-segments", icon: UsersThree, name: "Segment motoru", testId: "guest-segments-btn" },
        { id: "guest-journey", icon: SignIn, name: t("nav.guest_journey"), testId: "guest-journey-btn" },
        { id: "guest-rfm", icon: Target, name: "RFM segmentation", testId: "guest-rfm-btn" },
        { id: "guest-prefs", icon: Heart, name: "Guest preferences", testId: "guest-prefs-btn" },
        { id: "guest-portal-v2", icon: Users, name: "Guest self-modify", testId: "guest-portal-v2-btn" },

        { divider: true, label: "Loyalty" },
        { id: "loyalty", icon: Crown, name: t("nav.loyalty"), testId: "loyalty-btn", core: true },
        { id: "loyalty-tier", icon: Trophy, name: "Tier engine", testId: "loyalty-tier-btn" },
        { id: "loyalty-tiers-v2", icon: Crown, name: "Sadakat seviyeleri (Silver/Gold/Plat)", testId: "loyalty-tiers-v2-btn" },
        { id: "loyalty-v2", icon: Crown, name: "Loyalty referrals & packages", testId: "loyalty-v2-btn" },
        { id: "external-loyalty", icon: Crown, name: "Zincir Loyalty (Bonvoy/Honors)", testId: "external-loyalty-btn" },
        { id: "loyalty-auto", icon: Crown, name: "Loyalty auto-tier", testId: "loyalty-auto-btn" },
        { id: "birthday", icon: Sparkle, name: "Birthday discounts", testId: "birthday-btn" },

        { divider: true, label: "Feedback & Recovery" },
        { id: "surveys", icon: Star, name: t("nav.surveys"), testId: "surveys-btn" },
        { id: "mid-stay", icon: Smiley, name: "Mid-stay survey", testId: "mid-stay-btn" },
        { id: "service-recovery", icon: Notebook, name: "Service recovery", testId: "service-recovery-btn" },
        { id: "sr-voucher", icon: Tag, name: "Recovery vouchers", testId: "sr-voucher-btn" },
      ],
    },
    {
      label: "Marketing & Messaging",
      color: "text-stone-500",
      items: [
        { divider: true, label: "Campaigns" },
        { id: "campaigns", icon: Megaphone, name: t("nav.campaigns"), testId: "campaigns-btn", core: true },
        { id: "gap-filler", icon: MagicWand, name: "AI boşluk doldurma kampanyaları", testId: "gap-filler-btn" },
        { id: "demo-leads", icon: Funnel, name: "Demo talepleri (web sitesi)", testId: "demo-leads-btn" },
        { id: "lead-funnel", icon: Funnel, name: "Lead Funnel + Compset", testId: "lead-funnel-btn" },
        { id: "ab-test", icon: TestTube, name: "A/B testing", testId: "ab-test-btn" },
        { id: "attribution", icon: ChartBar, name: "Source attribution", testId: "attribution-btn" },
        { id: "web-push", icon: Bell, name: "Web push", testId: "web-push-btn" },
        { id: "marketing-videos", icon: FilmReel, name: "AI Pazarlama Videoları (Sora 2)", testId: "marketing-videos-btn" },
        { id: "brand-voice", icon: Megaphone, name: "Marka Sesi Stüdyosu", testId: "brand-voice-btn" },

        { divider: true, label: "Messaging" },
        { id: "messaging", icon: Envelope, name: t("nav.messaging"), testId: "messaging-btn", core: true },
        { id: "msg-templates", icon: Globe, name: "Message templates", testId: "msg-templates-btn" },
        { id: "pre-arrival", icon: Envelope, name: "Pre-arrival drip", testId: "pre-arrival-btn" },
        { id: "live-chat-inbox", icon: Headset, name: "Live Chat Inbox", testId: "live-chat-inbox-btn" },
        { id: "chatbot-automation", icon: Robot, name: "Chatbot motoru", testId: "chatbot-automation-btn" },
        { id: "automation", icon: Lightning, name: t("nav.automation"), testId: "automation-btn" },

        { divider: true, label: "AI Concierge" },
        { id: "concierge-inbox", icon: Robot, name: "Concierge inbox (AI)", testId: "concierge-inbox-btn" },
        { id: "concierge-analytics", icon: Robot, name: t("nav.concierge"), testId: "concierge-analytics-btn" },
        { id: "voice-concierge", icon: Microphone, name: "Voice concierge (Whisper)", testId: "voice-concierge-btn" },
        { id: "whatsapp-voice", icon: WhatsappLogo, name: "WhatsApp sesli concierge", testId: "whatsapp-voice-btn" },
        { id: "review-agent", icon: Star, name: "AI Yorum Yanıt Ajanı", testId: "review-agent-btn" },
      ],
    },
    {
      label: "Operations",
      color: "text-stone-500",
      items: [
        { divider: true, label: "Housekeeping" },
        { id: "housekeeping", icon: Broom, name: t("nav.housekeeping"), testId: "housekeeping-btn", core: true },
        { id: "hk-dispatch", icon: Lightning, name: "HK görev dağıtım panosu", testId: "hk-dispatch-btn" },

        { divider: true, label: "Maintenance & Ops" },
        { id: "ops-quick", icon: Lightning, name: "Quick ops", testId: "ops-quick-btn" },
        { id: "ops-v2", icon: Wrench, name: t("nav.ops_v2"), testId: "ops-v2-btn", core: true },
        { id: "operations-hub", icon: Gear, name: "Operations hub", testId: "operations-hub-btn" },
        { id: "pms-pro", icon: Sparkle, name: "PMS Pro (AI ops)", testId: "pms-pro-btn" },

        { divider: true, label: "Inventory & Assets" },
        { id: "asset-register", icon: Package, name: "Asset register", testId: "asset-register-btn" },
        { id: "stock-management", icon: Package, name: t("nav.stock"), testId: "stock-management-btn" },
        { id: "low-stock", icon: Package, name: "Low-stock alerts", testId: "low-stock-btn" },
        { id: "spaces", icon: SquaresFour, name: "Spaces (parking, meet)", testId: "spaces-btn" },
        { id: "smart-locks", icon: Key, name: t("nav.smart_locks"), testId: "smart-locks-btn" },
        { id: "smart-rooms", icon: Lightning, name: "Akıllı Oda (IoT)", testId: "smart-rooms-btn" },

        { divider: true, label: "Staff" },
        { id: "team-chat", icon: ChatText, name: "Team chat", testId: "team-chat-btn" },
        { id: "shift-scheduler", icon: CalendarBlank, name: "Shift scheduler", testId: "shift-scheduler-btn" },
        { id: "staff-performance", icon: Trophy, name: t("nav.staff_performance"), testId: "staff-performance-btn" },
        { id: "staff-ops", icon: Clock, name: "Staff clock-in & tips", testId: "staff-ops-btn" },

        { divider: true, label: "Quality Assurance" },
        { id: "glitch-log", icon: Warning, name: "Glitch log & devir", testId: "glitch-log-btn" },
        { id: "sops", icon: BookOpen, name: "SOP kütüphanesi", testId: "sops-btn" },
      ],
    },
    {
      label: "Revenue & rates",
      color: "text-stone-500",
      items: [
        { divider: true, label: "Pricing" },
        { id: "my-rates", icon: ChartLine, name: "My Rates (Daily Grid)", testId: "my-rates-btn", core: true },
        { id: "revenue", icon: ChartLine, name: "Revenue management", testId: "revenue-btn", core: true },
        { id: "profit-os", icon: Target, name: "Profit OS", testId: "profit-os-btn" },
        { id: "rate-manager", icon: ChartLine, name: "Rate manager", testId: "rate-manager-btn" },
        ...(user?.role !== "receptionist" ? [{ id: "rate-matrix", icon: Users, name: "Rate matrix", testId: "rate-matrix-btn" }] : []),
        { id: "rate-structure", icon: Tag, name: "Rate plans", testId: "rate-structure-btn" },
        { id: "open-pricing", icon: Stack, name: "Open Pricing matrisi", testId: "open-pricing-btn" },
        { id: "min-rates", icon: ShieldCheck, name: "Minimum fiyat koruması", testId: "min-rates-btn" },
        { id: "discount-stack", icon: Tag, name: "İndirim katmanları & net fiyat", testId: "discount-stack-btn" },

        { divider: true, label: "Forecast & Pace" },
        { id: "forecast", icon: ChartLine, name: t("nav.forecast"), testId: "forecast-btn" },
        { id: "forecast-v2", icon: TrendUp, name: "24-month forecast", testId: "forecast-v2-btn" },
        { id: "forecast-plans", icon: GitBranch, name: "Forecast planlama (sürüm & onay)", testId: "forecast-plans-btn" },
        { id: "pace-reports", icon: ChartLine, name: "Pace reports", testId: "pace-reports-btn" },

        { divider: true, label: "AI & Insights" },
        { id: "ai-pricing-v2", icon: Lightning, name: "AI pricing", testId: "ai-pricing-v2-btn" },
        { id: "base-curve", icon: ChartLine, name: "Baz fiyat eğrisi (18 ay)", testId: "base-curve-btn" },
        { id: "intraday-reprice", icon: Lightning, name: "Gün-içi re-price (pickup spike)", testId: "intraday-reprice-btn" },
        { id: "restriction-advisor", icon: LockKey, name: "AI kısıtlama önerileri (MLOS/CTA)", testId: "restriction-advisor-btn" },
        { id: "lost-demand", icon: UserMinus, name: "Kayıp talep (denials & regrets)", testId: "lost-demand-btn" },
        { id: "pricing-explain", icon: Brain, name: "AI pricing explainer", testId: "pricing-explain-btn" },
        { id: "anomaly", icon: Lightning, name: "Anomaly radar", testId: "anomaly-btn" },
        { id: "ai-predictions", icon: Sparkle, name: "AI predictions", testId: "ai-predictions-btn" },
        { id: "marketing-radar", icon: Lightning, name: "Pazarlama Fırsat Radarı", testId: "marketing-radar-btn" },
        { id: "demand-calendar", icon: Sparkle, name: "Talep Takvimi", testId: "demand-calendar-btn" },
        { id: "los-wash-metrics", icon: Coins, name: "LOS & Grup Wash & Modern Metrikler", testId: "los-wash-metrics-btn" },
        { id: "bi-chat", icon: Sparkle, name: "Veriye Sor (BI Chat)", testId: "bi-chat-btn" },
        { id: "parking-rms", icon: ChartLine, name: "Otopark RMS", testId: "parking-rms-btn" },

        { divider: true, label: "Market & Compset" },
        { id: "compset", icon: Target, name: "Compset yönetimi", testId: "compset-btn", core: true },
        { id: "parity-heatmap", icon: CalendarBlank, name: "Parity heatmap", testId: "parity-heatmap-btn" },
        { id: "ota-forecast", icon: TrendUp, name: "OTA stop-sell forecast", testId: "ota-forecast-btn" },
        { id: "channel-revenue", icon: Lightning, name: "Kanal yield yönetimi", testId: "channel-revenue-btn" },
        { id: "hotelrunner-live", icon: Lightning, name: "HotelRunner Canlı Bağlantı (ARI)", testId: "hotelrunner-live-btn" },
        { id: "rms-comparison", icon: Trophy, name: "Rakip Karşılaştırma (RMS)", testId: "rms-comparison-btn" },

        { divider: true, label: "Tools" },
        { id: "group-displacement", icon: Scales, name: "Grup displacement analizi", testId: "group-displacement-btn" },
        { id: "profit-pricing", icon: Coins, name: "Kâr-öncelikli fiyatlama", testId: "profit-pricing-btn" },
        { id: "decision-assurance", icon: ShieldCheck, name: "Decision Assurance (kanıtlı autopilot)", testId: "decision-assurance-btn" },
        { id: "data-quality", icon: Pulse, name: "Data Quality Autopilot", testId: "data-quality-btn" },
        { id: "group-sales", icon: Handshake, name: "Group Sales OS (RFP)", testId: "group-sales-btn" },
        { id: "overbooking-control", icon: Warning, name: "Overbooking & wash control", testId: "overbooking-control-btn" },
        { id: "room-type-forecast", icon: ChartLineUp, name: "Oda tipi forecast", testId: "room-type-forecast-btn" },
        { id: "abs-selling", icon: Bed, name: "Özellik bazlı satış (ABS)", testId: "abs-selling-btn" },
        { id: "revpam", icon: Briefcase, name: "Toplantı salonu RevPAM", testId: "revpam-btn" },
        { id: "function-space", icon: Briefcase, name: "Fonksiyon Alanı Motoru (Teklif & RevPAM)", testId: "function-space-btn" },
        { id: "rev-protection", icon: ShieldCheck, name: "Revenue protection", testId: "rev-protection-btn" },
        { id: "hurdle-lrv", icon: ShieldCheck, name: "Hurdle rate & LRV", testId: "hurdle-lrv-btn" },
        { id: "rm-lab", icon: ChartLine, name: "RM Lab", testId: "rm-lab-btn" },
        { id: "late-checkout-offer", icon: Clock, name: "Late checkout offers", testId: "late-checkout-offer-btn" },
        { id: "site-feasibility", icon: ChartLineUp, name: "Site feasibility & investor", testId: "site-feasibility-btn" },
        { id: "automation-hub", icon: Gear, name: "Otomasyon merkezi", testId: "automation-hub-btn" },
        { id: "leakage-audit", icon: ShieldCheck, name: "Gelir sızıntısı denetçisi", testId: "leakage-audit-btn" },
      ],
    },
    {
      label: "Channels & Distribution",
      color: "text-stone-500",
      items: [
        { id: "chmgr-hub", icon: Lightning, name: "Channel manager hub", testId: "chmgr-hub-btn", core: true },
        { id: "channels-v2", icon: CloudArrowUp, name: "Channel Manager v2", testId: "channels-v2-btn" },
        { id: "channel-settings", icon: Gear, name: t("nav.channel_settings"), testId: "channel-settings-btn" },
        { id: "channel-map-matrix", icon: Buildings, name: "Channel mappings", testId: "channel-map-matrix-btn" },
        { id: "channel-restrictions", icon: Lock, name: "Restrictions", testId: "channel-restrictions-btn" },
        { id: "channel-inbound", icon: Link, name: "Inbound reservations", testId: "channel-inbound-btn" },
        { id: "channel-parity", icon: Scales, name: "Parity monitor", testId: "channel-parity-btn" },
        { id: "channel-health", icon: Heart, name: "Kanal sağlık merkezi", testId: "channel-health-btn" },
        { id: "ota-health", icon: Heart, name: "OTA health", testId: "ota-health-btn" },
        { id: "channel-sync-queue", icon: ArrowsClockwise, name: "Sync queue", testId: "channel-sync-queue-btn" },
        { id: "synclog", icon: ArrowsClockwise, name: t("nav.synclog"), testId: "sync-log-btn" },
        { id: "pms-crs", icon: ArrowsClockwise, name: "PMS-CRS sync", testId: "pms-crs-btn" },
        { id: "siteminder", icon: PlugsConnected, name: "SiteMinder adapter", testId: "siteminder-btn" },
        { id: "ota-commission", icon: Lightning, name: "OTA Komisyon & Net Gelir", testId: "ota-commission-btn" },
        { id: "allotments", icon: Buildings, name: "Tur operatörü kontenjanları", testId: "allotments-btn" },
        { id: "b2b-agents", icon: Briefcase, name: "B2B portal (agents)", testId: "b2b-agents-btn" },
        { id: "agency-portal", icon: Briefcase, name: "Acenta portalı (TÜRSAB)", testId: "agency-portal-btn" },
        { id: "wholesaler-hub", icon: Globe, name: "Wholesaler ağı", testId: "wholesaler-hub-btn" },
      ],
    },
    {
      label: "Food & events",
      color: "text-stone-500",
      items: [
        { id: "pos", icon: Receipt, name: t("nav.pos"), testId: "pos-btn", core: true },
        { id: "kds", icon: ForkKnife, name: "Kitchen display", testId: "kds-btn" },
        { id: "menu-engineering", icon: ChartBar, name: "Menu engineering", testId: "menu-engineering-btn" },
        { id: "recipe-cogs", icon: Calculator, name: "Recipe COGS & modifiers", testId: "recipe-cogs-btn" },
        { id: "fnb-tabs", icon: ForkKnife, name: "F&B tab transfer", testId: "fnb-tabs-btn" },
        { id: "tipping", icon: Trophy, name: "Digital tipping", testId: "tipping-btn" },
        { id: "fnb-pos-hub", icon: PlugsConnected, name: "F&B POS entegrasyon hub", testId: "fnb-pos-hub-btn" },
        { id: "events", icon: CalendarBlank, name: "Events & rooms", testId: "events-btn" },
        { id: "conference-sc", icon: Briefcase, name: "Conference S&C", testId: "conference-sc-btn" },
        { id: "banquet-orders", icon: CalendarBlank, name: "Banquet event orders", testId: "banquet-orders-btn" },
        { id: "meetings-sales", icon: Briefcase, name: "Meeting & Events sales", testId: "meetings-sales-btn" },
        { id: "timeslots", icon: Sparkle, name: "Spa & activity slots", testId: "timeslots-btn" },
        { id: "spa-activities", icon: Sparkle, name: "Spa & aktivite rezervasyon", testId: "spa-activities-btn" },
        { id: "beach-pos", icon: Umbrella, name: "Beach POS (şezlong)", testId: "beach-pos-btn" },
        { id: "public-events", icon: Confetti, name: "Halka açık etkinlikler", testId: "public-events-btn" },
      ],
    },
    {
      label: "Finance",
      color: "text-stone-500",
      items: [
        { divider: true, label: "Accounting" },
        { id: "accounting", icon: Wallet, name: t("nav.accounting"), testId: "accounting-btn" },
        { id: "finance", icon: Wallet, name: "Finance overview", testId: "finance-btn", core: true },
        { id: "finance-pl", icon: ChartLine, name: "Profit & loss", testId: "finance-pl-btn" },
        { id: "cash-flow", icon: ChartLine, name: "Cash flow", testId: "cash-flow-btn" },
        { id: "budget-actual", icon: ChartBar, name: "Bütçe vs Gerçekleşen", testId: "budget-actual-btn" },
        { id: "expenses", icon: Receipt, name: "Expenses", testId: "expenses-btn" },
        { id: "payroll", icon: Wallet, name: "Payroll", testId: "payroll-btn" },

        { divider: true, label: "Payments" },
        { id: "payments", icon: Lightning, name: t("nav.payments"), testId: "payments-btn", core: true },
        { id: "preauth", icon: CreditCard, name: "Pre-auth holds", testId: "preauth-btn" },
        { id: "vcc-automation", icon: CreditCard, name: "VCC otomatik tahsilat", testId: "vcc-automation-btn" },
        { id: "owner-summary", icon: Receipt, name: "Aylık sahip özeti", testId: "owner-summary-btn" },
        { id: "chargeback", icon: Scales, name: "Chargebacks", testId: "chargeback-btn" },
        { id: "damage-protection", icon: ShieldCheck, name: "Hasar koruması (damage waiver)", testId: "damage-protection-btn" },
        { id: "card-vault", icon: CreditCard, name: "Card vault", testId: "card-vault-btn" },

        { divider: true, label: "Deposits" },
        { id: "deposit-policies", icon: ShieldCheck, name: "Deposit policies", testId: "deposit-policies-btn" },
        { id: "deposit-automation", icon: Lightning, name: "Deposit automation", testId: "deposit-automation-btn" },
        { id: "deposit-ledger", icon: Wallet, name: "Deposit ledger", testId: "deposit-ledger-btn" },

        { divider: true, label: "Ledger & Folios" },
        { id: "city-ledger", icon: Wallet, name: "City ledger (AR)", testId: "city-ledger-btn" },
        { id: "ar-recon", icon: Bank, name: "AR mutabakat agent'ı", testId: "ar-recon-btn" },
        { id: "digital-auth", icon: LockKey, name: "Dijital yetkilendirme", testId: "digital-auth-btn" },
        { id: "commission-recon", icon: Receipt, name: "Commission reconciliation", testId: "commission-recon-btn" },
        { id: "folio-live", icon: Receipt, name: "In-stay folio", testId: "folio-live-btn" },
        { id: "folio-split", icon: Receipt, name: "Folio split-billing", testId: "folio-split-btn" },
        { id: "cash-drawer", icon: Wallet, name: "Cash drawer", testId: "cash-drawer-btn" },
        { id: "gift-cards", icon: Tag, name: "Gift cards", testId: "gift-cards-btn" },
        { id: "currency", icon: CurrencyDollar, name: "Currency / FX", testId: "currency-btn" },
        { id: "currency-fx", icon: Globe, name: "Multi-currency settings", testId: "currency-fx-btn" },

        { divider: true, label: "Night Audit" },
        { id: "night-audit", icon: Moon, name: t("nav.night_audit"), testId: "night-audit-btn", core: true },
        { id: "night-audit-close", icon: Lock, name: "Close day", testId: "night-audit-close-btn" },

        { divider: true, label: "Tax & Compliance" },
        { id: "compliance", icon: ShieldCheck, name: "Compliance", testId: "compliance-btn" },
        { id: "tr-compliance", icon: FileText, name: "TR KBS & e-Invoice", testId: "tr-compliance-btn" },
        { id: "eu-compliance", icon: Globe, name: "EU police reports", testId: "eu-compliance-btn" },
        { id: "tax-config", icon: Receipt, name: "Tax configuration", testId: "tax-config-btn" },
        { id: "tax-presets", icon: Globe, name: "Tax presets library", testId: "tax-presets-btn" },
        { id: "tax-reports-v2", icon: Receipt, name: "Tax reports", testId: "tax-reports-v2-btn" },
        { id: "gdpr", icon: ShieldCheck, name: "GDPR data rights", testId: "gdpr-btn" },
        { id: "legal-docs", icon: ShieldCheck, name: "Legal documents", testId: "legal-docs-btn", roles: ["admin", "manager"] },
      ],
    },
    {
      label: "Reports & Analytics",
      color: "text-stone-500",
      items: [
        { divider: true, label: "Reviews & Sentiment" },
        { id: "reviews", icon: ChatText, name: t("nav.reviews"), testId: "nav-reviews", core: true },
        { id: "ai-reply-robot", icon: Sparkle, name: "AI Yanıt Robotu", testId: "ai-reply-robot-btn", core: true },
        { id: "review-sentiment", icon: Sparkle, name: "AI sentiment themes", testId: "review-sentiment-btn" },
        { id: "sentiment-heatmap", icon: ChartLineUp, name: "Sentiment heatmap", testId: "sentiment-heatmap-btn" },

        { divider: true, label: "Analytics" },
        { id: "analytics", icon: ChartBar, name: t("nav.analytics"), testId: "analytics-btn", core: true },
        { id: "reports", icon: CalendarBlank, name: t("nav.reports"), testId: "reports-btn" },
        { id: "reports-centre", icon: CalendarBlank, name: "Reports centre", testId: "reports-centre-btn", core: true },
        { id: "scheduled-reports", icon: Envelope, name: "Scheduled reports", testId: "scheduled-reports-btn" },

        { divider: true, label: "Exports & BI" },
        { id: "accounting-export", icon: ChartLine, name: "Accounting export", testId: "accounting-export-btn" },
        { id: "bi-feed", icon: ChartBar, name: "BI feed (Power BI / Tableau)", testId: "bi-feed-btn" },
        { id: "sustainability", icon: ChartLine, name: "Sustainability & ESG", testId: "sustainability-btn" },
        { id: "carbon-v2", icon: ChartLine, name: "Karbon Raporu (GHG Scope 1/2/3)", testId: "carbon-v2-btn" },

        { divider: true, label: "Workflow & Alerts" },
        { id: "templates", icon: FileText, name: t("nav.templates"), testId: "templates-btn" },
        ...(user?.role !== "receptionist" ? [{ id: "approvals", icon: ShieldCheck, name: t("nav.approvals"), testId: "approval-queue-btn" }] : []),
        { id: "alerts", icon: Bell, name: t("nav.alerts"), testId: "notification-settings-btn" },
        { id: "copilot", icon: Sparkle, name: "AI copilot library", testId: "copilot-btn" },
      ],
    },
    {
      label: "Portfolio & Owners",
      color: "text-stone-500",
      items: [
        { id: "multi-rollup", icon: Buildings, name: "Multi-property roll-up", testId: "multi-rollup-btn" },
        { id: "portfolio-board", icon: ArrowsClockwise, name: "Portföy panosu (tüm tesisler)", testId: "portfolio-board-btn" },
        { id: "chain-benchmark", icon: Trophy, name: "Zincir benchmark", testId: "chain-benchmark-btn" },
        { id: "brand-portal", icon: Buildings, name: "Brand portal (HQ)", testId: "brand-portal-btn" },
        { id: "owner-portal", icon: Buildings, name: "Sahip / yatırımcı portalı", testId: "owner-portal-btn" },
        { id: "security-owner", icon: Lock, name: "Owner portal", testId: "security-owner-btn" },
        { id: "owner-rates", icon: ArrowsClockwise, name: "Sahip fiyat panosu (iki yönlü)", testId: "owner-rates-btn" },
        { id: "owner-pulse-admin", icon: ArrowsClockwise, name: "Sahip portalı modülleri (Pulse)", testId: "owner-pulse-admin-btn" },
        { id: "vacation-rental", icon: House, name: "Vacation Rental (apart)", testId: "vacation-rental-btn" },
      ],
    },
    {
      label: "Apps & Integrations",
      color: "text-stone-500",
      items: [
        { divider: true, label: "Mobile & Guest Apps" },
        { id: "mobile-companion", icon: DeviceMobile, name: "Mobil görünüm (PWA)", testId: "mobile-companion-btn" },
        { id: "guest-app", icon: MapPin, name: t("nav.guest_app"), testId: "guest-app-btn" },
        { id: "kiosk-launch", icon: DeviceTablet, name: "Self-service kiosk", testId: "kiosk-launch-btn", launchUrl: true },
        { id: "self-checkin-v2", icon: SignIn, name: "Pre-arrival check-in", testId: "self-checkin-v2-btn" },
        { id: "self-checkin-auto", icon: Lightning, name: "Auto pre-arrival trigger", testId: "self-checkin-auto-btn" },
        { id: "lock-sdk", icon: Lock, name: "Hardware lock SDK", testId: "lock-sdk-btn" },

        { divider: true, label: "Integrations & API" },
        { id: "marketplace", icon: Storefront, name: "Marketplace (3rd-party apps)", testId: "marketplace-btn" },
        { id: "integrations", icon: PlugsConnected, name: t("nav.integrations"), testId: "integrations-btn" },
        { id: "api", icon: Key, name: t("nav.api"), testId: "api-connection-btn" },
        { id: "webhooks", icon: Code, name: t("nav.webhooks"), testId: "webhooks-btn" },
        { id: "public-api", icon: Code, name: "Developer portal", testId: "public-api-btn" },
        { id: "partner-webhooks", icon: PlugsConnected, name: "Partner webhooks & API keys", testId: "partner-webhooks-btn" },
        { id: "dev-portal", icon: Code, name: "Geliştirici portalı", testId: "dev-portal-btn" },
        { id: "ai-agents", icon: Robot, name: "Otonom AI Agent'lar", testId: "ai-agents-btn" },
        { id: "guide", icon: ArrowSquareOut, name: t("nav.guide"), testId: "integration-guide-btn" },
        { id: "mapping", icon: Buildings, name: t("nav.mapping"), testId: "property-mapping-btn" },
      ],
    },
    {
      label: "Settings & Admin",
      color: "text-stone-500",
      items: [
        { divider: true, label: "Setup" },
        { id: "setup-wizard", icon: Gear, name: t("nav.setup_wizard"), testId: "setup-wizard-btn" },
        { id: "onboarding", icon: MagicWand, name: "First-run wizard", testId: "onboarding-btn" },
        { id: "branding", icon: Palette, name: t("nav.branding"), testId: "branding-btn" },
        ...(user?.role === "admin" ? [{ id: "settings-hub", icon: Gear, name: "Settings hub", testId: "settings-hub-btn", core: true }] : []),
        ...(user?.role === "admin" ? [{ id: "error-sentinel", icon: Gear, name: "Hata Nöbetçisi", testId: "error-sentinel-btn" }] : []),

        { divider: true, label: "Team & Access" },
        ...(user?.role !== "receptionist" ? [{ id: "team", icon: Users, name: t("nav.team"), testId: "team-btn", core: true }] : []),
        ...(user?.role !== "receptionist" ? [{ id: "dept-shortcuts", icon: UsersThree, name: "Departman kısayolları", testId: "dept-shortcuts-btn" }] : []),
        ...(user?.role === "admin" ? [{ id: "contracts", icon: FileText, name: "Staff contracts", testId: "contracts-btn" }] : []),
        ...(user?.role !== "receptionist" ? [{ id: "onboarding-admin", icon: Users, name: "Onboarding review", testId: "onboarding-admin-btn" }] : []),
        ...(user?.role === "admin" ? [{ id: "roles-permissions", icon: ShieldCheck, name: "Roles & permissions", testId: "roles-permissions-btn" }] : []),
        { id: "two-factor-auth", icon: ShieldCheck, name: "Two-factor auth", testId: "two-factor-auth-btn" },
        ...(user?.role === "admin" ? [{ id: "ip-allowlist", icon: Globe, name: "IP allowlist", testId: "ip-allowlist-btn" }] : []),
        ...(user?.role === "admin" ? [{ id: "admin-panel", icon: ShieldCheck, name: t("nav.admin_panel"), testId: "admin-panel-btn" }] : []),

        { divider: true, label: "Data & System" },
        ...(user?.role === "admin" ? [{ id: "import-module", icon: Upload, name: "Import data", testId: "import-module-btn" }] : []),
        ...(user?.role === "admin" ? [{ id: "audit-trail", icon: ShieldCheck, name: "Audit trail", testId: "audit-trail-btn" }] : []),
        { id: "bug-tracker", icon: Bug, name: "Bug tracker", testId: "bug-tracker-btn" },

        { divider: true, label: "Help" },
        { id: "help-guide", icon: BookOpen, name: "Help & user guide", testId: "help-guide-btn" },
        { id: "mews-university", icon: GraduationCap, name: "HotelBox Academy", testId: "mews-university-btn" },
      ],
    },
  ];
}
