// Sidebar permission gating map — extracted from App.js (iter 386 refactor).
// Mapping testId → required MENU permission key. Items not listed stay visible.
export const SIDEBAR_PERM_MAP = {
    // Dashboard / Tasks / Calendar — broad visibility
    "dashboard-btn":          "dashboard_view",
    "my-tasks-btn":           "tasks_my_view",
    "sidebar-calendar":       "bookings_calendar_view",

    // Bookings
    "booking-engine-btn":         "bookings_view",
    "booking-engine-admin-btn":   "bookings_view",
    "arrivals-btn":               "bookings_view",
    "guest-profiles-btn":         "bookings_view",
    "guest-journey-btn":          "bookings_view",

    // Operations
    "operations-hub-btn":     "operations_reception_view",
    "housekeeping-btn":       "housekeeping_view",
    "hk-route-btn":           "housekeeping_view",
    "room-qr-btn":            "housekeeping_view",
    "service-recovery-btn":   "operations_reception_view",
    "late-checkout-btn":      "operations_reception_view",
    "no-show-btn":            "operations_reception_view",
    "walkin-btn":             "operations_reception_view",
    "guest-prefs-btn":        "operations_reception_view",
    "cleaning-checklists-btn":"housekeeping_view",
    "ops-quick-btn":          "operations_reception_view",
    "group-rooming-btn":      "view_bookings",
    "timeslots-btn":          "operations_reception_view",
    "staff-ops-btn":          "operations_reception_view",
    "rev-protection-btn":     "revenue_forecasting_view",
    "hurdle-lrv-btn":         "revenue_forecasting_view",
    "spaces-btn":             "operations_reception_view",
    "multi-rollup-btn":       "revenue_forecasting_view",
    "currency-btn":           "view_bookings",
    "b2b-agents-btn":         "view_bookings",
    "security-owner-btn":     "operations_reception_view",
    "preauth-btn":            "operations_reception_view",
    "chargeback-btn":         "operations_reception_view",
    "web-push-btn":           "operations_reception_view",
    "pms-crs-btn":            "operations_reception_view",
    "pms-pro-btn":            "operations_reception_view",
    "public-api-btn":         "operations_reception_view",
    "mid-stay-btn":           "operations_reception_view",
    "folio-live-btn":         "operations_reception_view",
    "ab-test-btn":            "operations_reception_view",
    "pre-arrival-btn":        "operations_reception_view",
    "menu-engineering-btn":   "operations_reception_view",
    "sr-voucher-btn":         "operations_reception_view",
    "folio-split-btn":        "operations_reception_view",
    "loyalty-auto-btn":       "operations_reception_view",
    "late-checkout-offer-btn":"operations_reception_view",
    "ota-forecast-btn":       "operations_reception_view",
    "ota-commission-btn":     "operations_reception_view",
    "availability-calendar-btn": "operations_reception_view",
    "direct-conversion-btn":  "operations_reception_view",
    "siteminder-btn":         "operations_reception_view",
    "external-loyalty-btn":   "operations_reception_view",
    "msg-templates-btn":      "operations_reception_view",
    "birthday-btn":           "operations_reception_view",
    "low-stock-btn":          "operations_reception_view",
    "rebook-btn":             "operations_reception_view",
    "stay-ext-btn":           "operations_reception_view",
    "long-stay-btn":          "operations_reception_view",
    "cancel-insurance-btn":   "operations_reception_view",
    "group-rooming-wiz-btn":  "operations_reception_view",
    "tax-reports-v2-btn":     "operations_reception_view",
    "ci-slots-btn":           "operations_reception_view",
    "tier1-dashboard-btn":    "operations_reception_view",
    "brand-portal-btn":       "operations_reception_view",
    "ops-v2-btn":             "maintenance_view",
    "forecast-v2-btn":        "revenue_forecasting_view",
    "anomaly-btn":            "revenue_forecasting_view",
    "pricing-explain-btn":    "revenue_forecasting_view",
    "tipping-btn":            "operations_reception_view",
    "guest-portal-v2-btn":    "operations_reception_view",
    "conference-sc-btn":      "operations_reception_view",
    "banquet-orders-btn":     "operations_reception_view",
    "copilot-btn":            "operations_reception_view",
    "image-ai-btn":           "housekeeping_view",
    "hk-turnover-btn":        "housekeeping_view",
    "fnb-tabs-btn":           "pos_view",
    "bi-feed-btn":            "revenue_forecasting_view",
    "ai-predictions-btn":     "revenue_forecasting_view",
    "channel-revenue-btn":    "revenue_forecasting_view",
    "sentiment-heatmap-btn":  "revenue_forecasting_view",
    "attribution-btn":        "revenue_forecasting_view",
    "tax-presets-btn":        "view_bookings",
    "maintenance-btn":        "maintenance_view",
    "shift-scheduler-btn":    "operations_shifts_view",
    "reception-report-btn":   "operations_reception_view",
    "pass-over-btn":          "operations_notes_view",
    "compliance-btn":         "operations_compliance_view",
    "tr-compliance-btn":      "operations_compliance_view",
    "e-invoice-btn":          "operations_compliance_view",
    "eu-compliance-btn":      "operations_compliance_view",
    "laundry-btn":            "laundry_reports_view",
    "stock-management-btn":   "view_laundry_stock",
    "logbook-btn":            "operations_notes_view",
    "lost-found-btn":         "operations_reception_view",
    "night-audit-btn":        "operations_reception_view",
    "events-btn":             "operations_reception_view",

    // Reports / Analytics / Forecast
    "reports-btn":            "reports_overview_view",
    "reports-centre-btn":     "reports_overview_view",
    "analytics-btn":          "revenue_analytics_performance_view",
    "forecast-btn":           "revenue_forecasting_view",
    "pace-reports-btn":       "revenue_forecasting_view",
    "ai-pricing-v2-btn":      "revenue_forecasting_view",
    "base-curve-btn":         "revenue_forecasting_view",
    "revenue-brain-btn":      "revenue_forecasting_view",
    "parity-heatmap-btn":     "revenue_forecasting_view",
    "morning-brief-btn":      "revenue_forecasting_view",
    "nightly-recap-btn":      "revenue_forecasting_view",
    "help-guide-btn":         null,
    "accounting-export-btn":  "revenue_forecasting_view",
    "rm-lab-btn":             "revenue_forecasting_view",
    "concierge-inbox-btn":    "revenue_forecasting_view",
    "group-requests-btn":     "view_bookings",
    "sustainability-btn":     "revenue_forecasting_view",
    "revenue-btn":            "revenue_dashboard_view",
    "profit-os-btn":          "revenue_profit_os_view",
    "approval-queue-btn":     "revenue_approvals_view",
    "setup-wizard-btn":       "revenue_wizard_view",
    "rate-manager-btn":       "rates_calendar_view",
    "my-rates-btn":           "rates_calendar_view",
    "scheduled-reports-btn":  "reports_overview_view",
    "staff-performance-btn":  "reports_overview_view",
    "concierge-analytics-btn":"reports_overview_view",

    // Finance
    "payroll-btn":            "finance_payroll_runs_view",
    "rate-matrix-btn":        "finance_payroll_runs_view",
    "expenses-btn":           "finance_expenses_view",
    "cash-flow-btn":          "finance_dashboard_view",
    "finance-btn":            "finance_dashboard_view",
    "finance-pl-btn":         "finance_dashboard_view",
    "payments-btn":           "finance_dashboard_view",
    "accounting-btn":         "finance_dashboard_view",

    // Channel Manager / Marketplace / Integrations
    "marketplace-btn":        "channel_manager_connections_view",
    "integrations-btn":       "channel_manager_connections_view",
    "channel-settings-btn":   "channel_manager_profiles_view",
    "property-mapping-btn":   "channel_manager_mapping_view",
    "sync-log-btn":           "channel_manager_sync_view",
    "api-connection-btn":     "channel_manager_connections_view",
    "integration-guide-btn":  "channel_manager_connections_view",
    "webhooks-btn":           "webhooks_view",
    "add-ons-btn":            "channel_manager_connections_view",

    // Guest-facing / Messaging / Marketing
    "messaging-btn":          "bookings_view",
    "guest-app-btn":          "bookings_view",
    "mobile-companion-btn":   "bookings_view",
    "whatsapp-voice-btn":     "bookings_view",
    "surveys-btn":            "bookings_view",
    "nav-reviews":            "bookings_view",
    "campaigns-btn":          "bookings_view",
    "loyalty-btn":            "bookings_view",
    "loyalty-tier-btn":       "bookings_view",
    "loyalty-v2-btn":         "bookings_view",
    "promo-codes-btn":        "bookings_view",
    "pos-btn":                "finance_dashboard_view",
    "kds-btn":                "finance_dashboard_view",
    "self-checkin-v2-btn":    "operations_reception_view",
    "smart-locks-btn":        "bookings_view",
    "smart-rooms-btn":        "bookings_view",
    "automation-btn":         "channel_manager_connections_view",
    "templates-btn":          "settings_roles_view",
    "website-templates-btn":  "settings_roles_view",
    "customize-template-btn": "settings_roles_view",
    "branding-btn":           "settings_roles_view",
    "policies-btn":           "settings_cancellation_policies_view",
    "notification-settings-btn": "settings_users_view",

    // Settings / People
    "team-btn":               "settings_users_view",
    "contracts-btn":          "settings_user_contracts_view",
    "onboarding-admin-btn":   "settings_users_view",
    "legal-docs-btn":         "settings_roles_view",
    "roles-permissions-btn":  "settings_roles_view",
    "admin-panel-btn":        "settings_users_view",
    "settings-hub-btn":       "settings_users_view",
    "bug-tracker-btn":        "system_feedback_view",
    "import-module-btn":      "settings_import_module_view",
    "audit-trail-btn":        "settings_roles_view",
  };
