// Template configurations for 10 hotel website templates
// 4x Booking.com style, 2x Airbnb, 2x Expedia, 2x Hotels.com

export const TEMPLATES = {
  // ===================== BOOKING.COM STYLE (4) =====================
  "booking-classic": {
    id: "booking-classic",
    name: "Classic Blue",
    platform: "Booking.com",
    description: "Trusted blue theme with prominent ratings, step-by-step booking flow",
    preview: "Classic hotel page with Booking.com's signature blue design",
    colors: {
      primary: "#003B95",
      primaryHover: "#00264D",
      accent: "#006CE4",
      accentHover: "#0056B3",
      success: "#008009",
      urgency: "#D32F2F",
      headerBg: "#003B95",
      headerText: "#FFFFFF",
      heroBg: "linear-gradient(135deg, #003B95 0%, #0057B8 100%)",
      heroOverlay: "rgba(0, 27, 66, 0.55)",
      cardBg: "#FFFFFF",
      bodyBg: "#F5F7FA",
      ratingBg: "#003B95",
      ratingText: "#FFFFFF",
      badgeBg: "#EDFCF0",
      badgeText: "#008009",
      priceBg: "#F5F7FA",
    },
    fonts: { heading: "Outfit, sans-serif", body: "Manrope, sans-serif" },
    borderRadius: "8px",
    heroStyle: "image-overlay",
    layout: "standard",
    showRatingBadge: true,
    showUrgency: true,
    showFreeCancellation: true,
    showSecurityBadges: true,
    sectionOrder: ["hero", "search", "rooms", "reviews", "trust", "footer"],
  },

  "booking-business": {
    id: "booking-business",
    name: "Business Navy",
    platform: "Booking.com",
    description: "Corporate dark navy theme for business hotels and conference venues",
    preview: "Professional feel for business travellers",
    colors: {
      primary: "#1A1F36",
      primaryHover: "#0F1225",
      accent: "#5469D4",
      accentHover: "#3D51B5",
      success: "#3ECF8E",
      urgency: "#FF6B6B",
      headerBg: "#1A1F36",
      headerText: "#FFFFFF",
      heroBg: "linear-gradient(135deg, #1A1F36 0%, #2D3561 100%)",
      heroOverlay: "rgba(26, 31, 54, 0.6)",
      cardBg: "#FFFFFF",
      bodyBg: "#F6F9FC",
      ratingBg: "#5469D4",
      ratingText: "#FFFFFF",
      badgeBg: "#E8FDF0",
      badgeText: "#3ECF8E",
      priceBg: "#F6F9FC",
    },
    fonts: { heading: "Outfit, sans-serif", body: "Manrope, sans-serif" },
    borderRadius: "6px",
    heroStyle: "image-overlay",
    layout: "standard",
    showRatingBadge: true,
    showUrgency: true,
    showFreeCancellation: true,
    showSecurityBadges: true,
    sectionOrder: ["hero", "search", "rooms", "reviews", "trust", "footer"],
  },

  "booking-resort": {
    id: "booking-resort",
    name: "Resort Paradise",
    platform: "Booking.com",
    description: "Tropical resort theme with warm tones and relaxation vibes",
    preview: "Perfect for beach resorts, spas, and tropical getaways",
    colors: {
      primary: "#0C6E5D",
      primaryHover: "#094D42",
      accent: "#0FA68B",
      accentHover: "#0D8A73",
      success: "#2E9E5A",
      urgency: "#E65100",
      headerBg: "#0C6E5D",
      headerText: "#FFFFFF",
      heroBg: "linear-gradient(135deg, #0C6E5D 0%, #1A9B84 100%)",
      heroOverlay: "rgba(0, 40, 30, 0.45)",
      cardBg: "#FFFFFF",
      bodyBg: "#F0F7F5",
      ratingBg: "#0C6E5D",
      ratingText: "#FFFFFF",
      badgeBg: "#E3F5EF",
      badgeText: "#0C6E5D",
      priceBg: "#F0F7F5",
    },
    fonts: { heading: "Outfit, sans-serif", body: "Manrope, sans-serif" },
    borderRadius: "12px",
    heroStyle: "image-overlay",
    layout: "standard",
    showRatingBadge: true,
    showUrgency: true,
    showFreeCancellation: true,
    showSecurityBadges: true,
    sectionOrder: ["hero", "search", "rooms", "reviews", "trust", "footer"],
  },

  "booking-boutique": {
    id: "booking-boutique",
    name: "Boutique Elegant",
    platform: "Booking.com",
    description: "Refined boutique hotel theme with gold accents and sophisticated feel",
    preview: "For luxury boutique hotels and intimate properties",
    colors: {
      primary: "#2C2C2C",
      primaryHover: "#1A1A1A",
      accent: "#B8860B",
      accentHover: "#996F09",
      success: "#4A7C59",
      urgency: "#C41E3A",
      headerBg: "#2C2C2C",
      headerText: "#FFFFFF",
      heroBg: "linear-gradient(135deg, #2C2C2C 0%, #4A4A4A 100%)",
      heroOverlay: "rgba(20, 20, 20, 0.5)",
      cardBg: "#FFFFFF",
      bodyBg: "#FAFAF8",
      ratingBg: "#B8860B",
      ratingText: "#FFFFFF",
      badgeBg: "#F5F0E5",
      badgeText: "#8B6914",
      priceBg: "#FAF8F5",
    },
    fonts: { heading: "Outfit, sans-serif", body: "Manrope, sans-serif" },
    borderRadius: "4px",
    heroStyle: "image-overlay",
    layout: "standard",
    showRatingBadge: true,
    showUrgency: false,
    showFreeCancellation: true,
    showSecurityBadges: true,
    sectionOrder: ["hero", "search", "rooms", "reviews", "trust", "footer"],
  },

  // ===================== AIRBNB STYLE (2) =====================
  "airbnb-modern": {
    id: "airbnb-modern",
    name: "Modern Stay",
    platform: "Airbnb",
    description: "Clean white design with photo grid and host profile section",
    preview: "Minimal, photo-forward design like Airbnb listings",
    colors: {
      primary: "#FF385C",
      primaryHover: "#E0294E",
      accent: "#FF385C",
      accentHover: "#D92048",
      success: "#008A05",
      urgency: "#C13515",
      headerBg: "#FFFFFF",
      headerText: "#222222",
      heroBg: "#FFFFFF",
      heroOverlay: "transparent",
      cardBg: "#FFFFFF",
      bodyBg: "#FFFFFF",
      ratingBg: "#FF385C",
      ratingText: "#FFFFFF",
      badgeBg: "#F7F7F7",
      badgeText: "#222222",
      priceBg: "#F7F7F7",
    },
    fonts: { heading: "Outfit, sans-serif", body: "Manrope, sans-serif" },
    borderRadius: "12px",
    heroStyle: "photo-grid",
    layout: "airbnb",
    showRatingBadge: true,
    showUrgency: false,
    showFreeCancellation: true,
    showSecurityBadges: true,
    sectionOrder: ["photo-grid", "info", "rooms", "amenities", "reviews", "location", "footer"],
  },

  "airbnb-experience": {
    id: "airbnb-experience",
    name: "Experience Plus",
    platform: "Airbnb",
    description: "Immersive experience-driven layout with full-width photos and local tips",
    preview: "Storytelling-driven design for unique properties",
    colors: {
      primary: "#E21C5E",
      primaryHover: "#C2174F",
      accent: "#E21C5E",
      accentHover: "#B8174F",
      success: "#008A05",
      urgency: "#C13515",
      headerBg: "#FFFFFF",
      headerText: "#1A1A1A",
      heroBg: "#FFFFFF",
      heroOverlay: "transparent",
      cardBg: "#FFFFFF",
      bodyBg: "#FAFAFA",
      ratingBg: "#222222",
      ratingText: "#FFFFFF",
      badgeBg: "#F0F0F0",
      badgeText: "#333333",
      priceBg: "#FAFAFA",
    },
    fonts: { heading: "Outfit, sans-serif", body: "Manrope, sans-serif" },
    borderRadius: "16px",
    heroStyle: "photo-grid",
    layout: "airbnb",
    showRatingBadge: true,
    showUrgency: false,
    showFreeCancellation: true,
    showSecurityBadges: true,
    sectionOrder: ["photo-grid", "info", "rooms", "amenities", "reviews", "location", "footer"],
  },

  // ===================== EXPEDIA STYLE (2) =====================
  "expedia-classic": {
    id: "expedia-classic",
    name: "Expedia Deals",
    platform: "Expedia",
    description: "Yellow accent deals-focused theme with bundle offers and member pricing",
    preview: "Deal-driven layout similar to Expedia's hotel pages",
    colors: {
      primary: "#1D3C6E",
      primaryHover: "#15305A",
      accent: "#F5B21F",
      accentHover: "#E0A317",
      success: "#1D7B2E",
      urgency: "#D93025",
      headerBg: "#1D3C6E",
      headerText: "#FFFFFF",
      heroBg: "linear-gradient(135deg, #1D3C6E 0%, #2B5BA8 100%)",
      heroOverlay: "rgba(15, 30, 60, 0.5)",
      cardBg: "#FFFFFF",
      bodyBg: "#F4F6F8",
      ratingBg: "#1D7B2E",
      ratingText: "#FFFFFF",
      badgeBg: "#FFF8E1",
      badgeText: "#B8860B",
      priceBg: "#FFF8E1",
    },
    fonts: { heading: "Outfit, sans-serif", body: "Manrope, sans-serif" },
    borderRadius: "8px",
    heroStyle: "image-overlay",
    layout: "expedia",
    showRatingBadge: true,
    showUrgency: true,
    showFreeCancellation: true,
    showSecurityBadges: true,
    sectionOrder: ["hero", "search", "deals", "rooms", "reviews", "trust", "footer"],
  },

  "expedia-premium": {
    id: "expedia-premium",
    name: "Expedia VIP",
    platform: "Expedia",
    description: "Premium luxury tier with VIP perks, concierge service highlights",
    preview: "Elevated experience for premium hotel properties",
    colors: {
      primary: "#1B2640",
      primaryHover: "#111A2E",
      accent: "#C9A84C",
      accentHover: "#B5953F",
      success: "#2E7D32",
      urgency: "#D32F2F",
      headerBg: "#1B2640",
      headerText: "#FFFFFF",
      heroBg: "linear-gradient(135deg, #1B2640 0%, #2A3D66 100%)",
      heroOverlay: "rgba(10, 15, 30, 0.5)",
      cardBg: "#FFFFFF",
      bodyBg: "#F8F7F4",
      ratingBg: "#C9A84C",
      ratingText: "#1B2640",
      badgeBg: "#F5F0E0",
      badgeText: "#8B7020",
      priceBg: "#F8F7F4",
    },
    fonts: { heading: "Outfit, sans-serif", body: "Manrope, sans-serif" },
    borderRadius: "8px",
    heroStyle: "image-overlay",
    layout: "expedia",
    showRatingBadge: true,
    showUrgency: false,
    showFreeCancellation: true,
    showSecurityBadges: true,
    sectionOrder: ["hero", "search", "rooms", "reviews", "trust", "footer"],
  },

  // ===================== HOTELS.COM STYLE (2) =====================
  "hotels-rewards": {
    id: "hotels-rewards",
    name: "Hotels Rewards",
    platform: "Hotels.com",
    description: "Red accent rewards-focused theme with loyalty stamps and member pricing",
    preview: "Loyalty-driven design with Hotels.com's signature red",
    colors: {
      primary: "#D32F2F",
      primaryHover: "#B71C1C",
      accent: "#D32F2F",
      accentHover: "#B71C1C",
      success: "#2E7D32",
      urgency: "#E65100",
      headerBg: "#D32F2F",
      headerText: "#FFFFFF",
      heroBg: "linear-gradient(135deg, #D32F2F 0%, #E64545 100%)",
      heroOverlay: "rgba(100, 10, 10, 0.45)",
      cardBg: "#FFFFFF",
      bodyBg: "#FAFAFA",
      ratingBg: "#D32F2F",
      ratingText: "#FFFFFF",
      badgeBg: "#FFEBEE",
      badgeText: "#C62828",
      priceBg: "#FFF3F0",
    },
    fonts: { heading: "Outfit, sans-serif", body: "Manrope, sans-serif" },
    borderRadius: "10px",
    heroStyle: "image-overlay",
    layout: "hotels",
    showRatingBadge: true,
    showUrgency: true,
    showFreeCancellation: true,
    showSecurityBadges: true,
    sectionOrder: ["hero", "search", "rooms", "reviews", "trust", "footer"],
  },

  "hotels-family": {
    id: "hotels-family",
    name: "Family Friendly",
    platform: "Hotels.com",
    description: "Warm family-focused theme highlighting child-friendly amenities",
    preview: "Designed for family travellers with kid-friendly highlights",
    colors: {
      primary: "#5C6BC0",
      primaryHover: "#3F51B5",
      accent: "#FF7043",
      accentHover: "#E64A19",
      success: "#43A047",
      urgency: "#EF5350",
      headerBg: "#5C6BC0",
      headerText: "#FFFFFF",
      heroBg: "linear-gradient(135deg, #5C6BC0 0%, #7986CB 100%)",
      heroOverlay: "rgba(30, 40, 90, 0.45)",
      cardBg: "#FFFFFF",
      bodyBg: "#F5F5FA",
      ratingBg: "#FF7043",
      ratingText: "#FFFFFF",
      badgeBg: "#FFF3E0",
      badgeText: "#E65100",
      priceBg: "#F5F5FA",
    },
    fonts: { heading: "Outfit, sans-serif", body: "Manrope, sans-serif" },
    borderRadius: "14px",
    heroStyle: "image-overlay",
    layout: "hotels",
    showRatingBadge: true,
    showUrgency: true,
    showFreeCancellation: true,
    showSecurityBadges: true,
    sectionOrder: ["hero", "search", "rooms", "reviews", "trust", "footer"],
  },
};

export const TEMPLATE_LIST = Object.values(TEMPLATES);

export const getTemplate = (id) => TEMPLATES[id] || TEMPLATES["booking-classic"];

export const PLATFORM_GROUPS = [
  { name: "Booking.com Style", templates: ["booking-classic", "booking-business", "booking-resort", "booking-boutique"] },
  { name: "Airbnb Style", templates: ["airbnb-modern", "airbnb-experience"] },
  { name: "Expedia Style", templates: ["expedia-classic", "expedia-premium"] },
  { name: "Hotels.com Style", templates: ["hotels-rewards", "hotels-family"] },
];
